apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: meru
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: meru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: meru
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      upstream meru-app-compute {
        server meru-app-compute:80;
      }
      server {
        listen 80;
        location / {
          proxy_pass http://meru-app-compute;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }